#pragma once

#define LOADER_CORE_VER_REV   BUILD_VERSION_REV
#define LOADER_CORE_VER_NAME  BUILD_VERSION_NAME
#define LOADER_CORE_VER_MAJOR GW2AL_API_VER_MAJOR
#define LOADER_CORE_VER_MINOR GW2AL_API_VER_MINOR